services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blablabook_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    command: sh -c "npm run db:create && npm run db:seed && npm start"
  test:
    build: .
    volumes:
      - .:/app
    command: npm run test
  database:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blablabook"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: blablabook
      POSTGRES_PASSWORD: blablabook
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 