services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blablabook_app
    environment:
      PG_URL:${PG_URL}
    command: >
      sh -c "node migrations/createTables.js && npm start"
    ports:
      - "3001:3004"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: blablabook_db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
