name: Lancement de l'application

on:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch the code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dépendancies
      run: npm install

    - name: Start application
      run: npm start 
